### PR TITLE
ArrayAcc

### PR DESCRIPTION
**Pull request by tonyday567**

### CODE REVIEW

**Comment by tonyday567** [comment]
I stripped it all back to just fromList and show, in order to get the shape type right.  It's almost there but I get:

```
let a = (fromList [1..24]) :: ArrayAcc '[2,3,4] Int

<interactive>:1:10: error:
    • No instance for (AR.Shape (((A.Z A.:. Int) A.:. Int) A.:. Int))
        arising from a use of ‘fromList’
```

Not sure how to approach this.

I think accelerate integration with numhask needs to proceed roughly as:

- [ ] get the type-level shapes right
- [ ] implement the basic numhask heirarchy (should be easy)
- [ ] implement the basic array computations (slice, rows, mmult etc)
- [ ] sit back and think about the naperian/representable bits, and be prepared to abandon them, as having a vanilla Functor instance is, in part, the point of Representable
- [ ] do some performance work

**Comment by o1lo01ol1o** [comment]
Issue is probably using that `AR.listToShape` function, that `Shape` constraint may be exclusively internal.

**Comment by o1lo01ol1o** [comment]
👍

**Comment by o1lo01ol1o** [comment]
Are you meditating on the naperian bits?  Is the hierarchy complete? Is there a way forward on the array computations?  

Have a project that I would like an accelerate + numhask hierarchy in :D

**Pull request merged**
